### ISSUE TITLE
Markdown: Top level description should not be styled as list item

### ISSUE THREAD

**Issue by drodil** [thearegee/bookworms#4]
When adding description to the top level of the yaml file, the description is rendered in markdown as list item. This looks a bit funny and instead it should add the description as just text under the label. 

For example
```yaml
label: My Bookmarks
description: Collection of my bookmarks
folders:
  - label: General
     bookmarks:
        - label: Google
           href: https://www.google.com
 ```
Should render as

```md
# My bookmarks

Collection of my bookmarks

## General

* [Google](https://www.google.com)
```

Currently it renders like:

```md
# My bookmarks

* Collection of my bookmarks

## General

* [Google](https://www.google.com)
```
