### ISSUE TITLE
Markdown: Subfolder heading level is wrong

### ISSUE THREAD

**Issue by drodil** [thearegee/bookworms#5]
When adding sub folders to the yaml file the markdown heading level should increase

For example
```yaml
label: My Bookmarks
description: Collection of my bookmarks
folders:
  - label: General
     folders:
        - label: Search engines
          bookmarks:
            - label: Google
               href: https://www.google.com
 ```
Should render as

```md
# My bookmarks

Collection of my bookmarks

## General

### Search engines

* [Google](https://www.google.com)
```

Currently it renders as:

```md
# My bookmarks

Collection of my bookmarks

## General

## Search engines

* [Google](https://www.google.com)
```
