### ISSUE TITLE
Markdown: Folders and bookmarks under same parent are not rendered correctly

### ISSUE THREAD

**Issue by drodil** [thearegee/bookworms#6]
When adding both folders and bookmarks under the same parent, the markdown is just appending the bookmarks under the last folder. In markdown the bookmarks should be first and then the subfolders while in the browsers.html the other way around

For example
```yaml
label: My Bookmarks
description: Collection of my bookmarks
folders:
  - label: General
     bookmarks:
        - label: Google
           href: https://www.google.com
     folders:
        - label: Subfolder
           bookmarks:
               - label: Yahoo
                  href: https://www.yahoo.com
 ```
Should render as

```md
# My bookmarks

Collection of my bookmarks

## General

* [Google](https://www.google.com)

### Subfolder

* [Yahoo](https://www.yahoo.com)

```

Currently it renders as:

```md
# My bookmarks

Collection of my bookmarks

## General

## Subfolder

* [Yahoo](https://www.yahoo.com)

* [Google](https://www.google.com)

```
