### ISSUE TITLE
Import other YAMLs into a template YAML

### ISSUE THREAD

**Issue by robinglen** [thearegee/bookworms#9]
There is a command called `merge` this is used to merge multiple bookmark YAMLs but this can be a little restrictive for deep nesting multiple files.

For example I have my own personal bookmarks that are in their own repo but then I work with multiple companies who have their own bookmark YAMLs repos. You can merge these but it doesn't give you much control on the structure. I think a good solution might be a main YAML with place holders.

```YAML
label: gullwing.io
description: Bookmarks for gullwing.io
folders:
  - label: personal
    description: Tools used by Collagerie
    {{ https://link-to-my-bookmarks }}
  - label: clients
    description: different companies I work with
  folders:
  {{ ./local-client-1 }}
  {{ https://link-to-remote-client-2 }}
```

These types of YAML files would then need to be interpolated fetching local or remote YAML files then merging them into the "template YAML". Once there is a complete YAML this can then be converted into the required file types.

This should be pretty straightforward but maybe the indentation will cause some issues.
